version=${project.version}

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.de.andrenitze=DEBUG

# Optional logging configuration
LOG_PATH=logs
LOG_FILE=logs/softpro.log
LOG_PATTERN=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n