version=${project.version}

spring.datasource.url=jdbc:mariadb://localhost:3306/thatsoftwaregame?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=game
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=DEBUG
logging.level.de.andrenitze.softpro=DEBUG