package de.andrenitze.softpro.types;

public enum EventType {
    ASSIGN_EMPLOYEE,
    JOIN_TENDER,
    PLAYER_READY,
    ROUND_STARTED,
    UNASSIGN_EMPLOYEE,
    GAME_OVER,
    UPDATE_STATE,
    NEW_TENDER,
    NEW_FUNDS,
    PROJECT_RECEIVED,
    TENDER_CLOSED,
    OBJECTIVES_UPDATED,
    PROJECT_UPDATED,
    PLAYER_UPDATED,
    NEW_STORY_ELEMENT,
    UPDATE_LOBBY,
    T,
    EMPLOYEE_UPDATED,
    PLAYER_NAME_UPDATED,
}