package de.andrenitze.softpro.types;

public enum EventType {
    ASSIGN_EMPLOYEE,
    JOIN_TENDER,
    START_GAME,
    START_ROUND,
    UNASSIGN_EMPLOYEE,
    GAME_OVER,
    UPDATE_STATE,
    NEW_TENDER,
    NEW_FUNDS,
    PROJECT,
    CLOSE_TENDER,
    UPDATE_OBJECTIVES,
    PROJECT_UPDATED,
    UPDATE_PLAYER,
    NEW_STORY_ELEMENT,
}